#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Skugubaev\CalcCommand;

$app = new Application("Welcome from console", "v1.0.0");
$app->add(new CalcCommand());
$app->run();
